apiVersion: aws.devplatforms.io/v1alpha1
kind: EKSCluster
metadata:
  name: dev-cluster
  namespace: crossplane-system
spec:
  parameters:
    clusterVersion: "1.28"
    region: us-east-1
    cidrBlock: 10.0.0.0/16
  writeConnectionSecretToRef:
    name: eks-cluster-kubeconfig
    namespace: production
