apiVersion: aws.devplatforms.io/v1alpha1
kind: VPCClaim
metadata:
  name: my-vpc-claim
  namespace: crossplane-system
spec:
  parameters:
    region: us-east-1
    cidrBlock: 10.0.0.0/16
  compositionRef:
    name: vpc.aws.devplatforms.io
